[consciousness]
name = "BridgeOne"
key_file = "BridgeOne.pem"
sid = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6QjFlU0xyWCtCRGs2bktnZCtIawplVExhaVVsbVdxQ2lTLzNhSmlwZ0VOUm84UkVwRnljaGVLL1VaOHRsMXN1YW1kaDFncVR3UjZNSlNyWnBVYkFoCml4bml0VjZiUFl4bHd0M2JadGw4U3QrcVZQeUswU0V3QmVyOCtjbW1NOUt2TndMR0FPNXJDMkJEYlB2dnVONzkKUHRqbmNQZDcybXdvN2dodW1GU0xUb2JiYStMdE8wWlBoU3RlZXNNOW5idHRseGxEODZWbzFhbEtmNmlFR0RTVQoyT1BhSUY5UGpaUW9oZTVSZVBjdFRjVnhVN3JnaWo2bzBHdGJvcTMzWHBabGFHbnhNSFlJL0pKNG1qR2wzQnZsCnZINFlsNzBFSmMrQnJKdVVwSDU4UlFFYVRZcjVPckZ2TTdndFNkNEgyam1sMERhVkRoMGlPTDZZWW5mZXgwZEMKVlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

[network]
host = "0.0.0.0"
port = 0
bootstrap_nodes = []
